---
title: "Informe Torres del Paine"
author: "Derek Corcoran"
date: "December 16, 2015"
output: pdf_document
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(RNetLogo)
library(dplyr)
library(ggplot2)
library(knitr)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}

nl.path <- "C:/Program Files (x86)/NetLogo 5.2.1"
NLStart(nl.path, gui=TRUE)

model.path <- file.path("C:/Users/corcoranbarriosd/Documents/Paine/total.nlogo")
NLLoadModel(model.path)
NLCommand("load-gis")
NLCommand("get-paths")
NLCommand("setup")

NLDoCommand(351, "go")

DF <- NLDoReport(10, "go", c("(ticks + 600) / (ticks-to-an-hour * 24)","count tourists", "count tourists-on patch -19 -170", "count tourists-on patch -15 -171", "(count tourists-on patch -50 -80) + (count tourists-on patch -48 -78)", "count tourists-on patch -115 4", "(count tourists-on patch -11 -17) + (count tourists-on patch -8 -25)", "count tourists-on patch -5 39", "count tourists-on patch 22 -21", "count tourists-on patch 36 -22", "count tourists-on patch 96 57", "count tourists-on patch 73 79", "(count tourists-on patch 115 32) + (count tourists-on patch 115 33)", "count tourists-on patch 129 54","(([excess] of patch 96 57)/ ticks-to-an-hour )","((([excess] of patch 115 32)/ ticks-to-an-hour ) + (([excess] of patch 115 33)/ ticks-to-an-hour )) * 0.5", "(([excess] of patch 36 -22)/ ticks-to-an-hour )", "(([excess] of patch 22 -21)/ ticks-to-an-hour )"), as.data.frame = TRUE, df.col.names = c("Days", "Total.tourists", "Tourists1", "Tourists2", "Tourists3", "Tourists4", "Tourists6", "Tourists7", "Tourists9", "Tourists10", "Tourists11", "Tourists12", "Tourists13", "Tourists14", "Exceso-Chileno", "Exceso-torre-cn","Exceso-cuernos", "Exceso-Frances"))
NLCommand("clear-all")
NLQuit()
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
DF <- mutate(DF, day = ceiling(Days))
DF <- mutate(DF, time = Days-(day-1))

summary(DF)

SumDF <-summarise(group_by(DF, day), mean = mean(Total.tourists), max.tourists = max(Total.tourists))

ggplot(SumDF, aes(x= day, y = mean)) + geom_point() + geom_smooth()

#DF <- filter(DF, day > 6)
DF$day <- as.factor(DF$day)
DF$time <- as.factor(DF$time)
AV.day <- summarise(group_by(DF, time), mean = mean(Total.tourists), SD = sd(Total.tourists))
Av.day <- mutate(AV.day, up = mean + SD, low = mean - SD)
ggplot(Av.day, aes(x= as.numeric(time), y = mean)) + geom_smooth()
```
